# Generated by Django 2.1.7 on 2019-02-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=40, null=True, verbose_name='Access Token')),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6)),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('password', models.CharField(blank=True, max_length=40, null=True, verbose_name='密码')),
                ('student_card_url_front', models.CharField(blank=True, max_length=100, null=True, verbose_name='学生证正面')),
                ('student_card_url_back', models.CharField(blank=True, max_length=100, null=True, verbose_name='学生证反面')),
                ('avatar', models.CharField(default='http://wsmpage.cn/reddot/2f9c84d4-67b4-4de2-a991-620466b73ccd', max_length=100, verbose_name='用户头像')),
                ('school', models.CharField(default='', max_length=30, verbose_name='学校')),
                ('city', models.CharField(default='', max_length=30, verbose_name='城市')),
                ('state', models.CharField(choices=[('1', '研究生'), ('0', '本科生')], default='0', max_length=6)),
                ('level', models.CharField(choices=[('1', 'level_1'), ('2', 'level_2'), ('3', 'level_3'), ('4', 'level_4'), ('5', 'level_5'), ('6', 'level_6'), ('7', 'level_7')], default='1', max_length=6)),
            ],
        ),
    ]
