# Generated by Django 2.1.7 on 2019-02-21 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190221_1523'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=100, null=True, verbose_name='第一项')),
                ('second', models.CharField(blank=True, max_length=100, null=True, verbose_name='第二项')),
                ('third', models.CharField(blank=True, max_length=100, null=True, verbose_name='第三项')),
                ('fourth', models.CharField(blank=True, max_length=100, null=True, verbose_name='第四项')),
                ('fifth', models.CharField(blank=True, max_length=100, null=True, verbose_name='第五项')),
                ('sixth', models.CharField(blank=True, max_length=100, null=True, verbose_name='第六项')),
                ('state1', models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=6, verbose_name='第一项完成状况')),
                ('state2', models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=6, verbose_name='第二项完成状况')),
                ('state3', models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=6, verbose_name='第三项完成状况')),
                ('state4', models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=6, verbose_name='第四项完成状况')),
                ('state5', models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=6, verbose_name='第五项完成状况')),
                ('state6', models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=6, verbose_name='第六项完成状况')),
                ('type', models.CharField(choices=[('1', '周计划'), ('0', '日计划')], default='0', max_length=6, verbose_name='计划类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '计划表',
                'verbose_name_plural': '计划表',
            },
        ),
    ]
