# Generated by Django 2.1.7 on 2019-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_plantable'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantable',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='计划表uuid'),
        ),
    ]
