# Generated by Django 2.1.7 on 2019-02-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantable',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', to_field='phone', verbose_name='创建用户'),
        ),
    ]
