# Generated by Django 2.1.7 on 2019-02-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20190225_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
