# Generated by Django 2.1.7 on 2019-02-25 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190225_1608'),
        ('source', '0007_auto_20190225_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('text', models.TextField(blank=True, null=True, verbose_name='标题')),
                ('create_user', models.ForeignKey(blank=True, help_text='创建者的手机号', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', to_field='phone', verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '考研路',
                'verbose_name_plural': '考研路',
            },
        ),
    ]
