# Generated by Django 2.1.7 on 2019-02-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_userrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
