# Generated by Django 2.1.7 on 2019-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_userexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='img1_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='用户心得/吐槽配图1'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='img2_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='用户心得/吐槽配图2'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='img3_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='用户心得/吐槽配图3'),
        ),
    ]
