# Generated by Django 2.1.7 on 2019-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='发送者手机号')),
                ('s_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='发送者昵称')),
                ('r_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='接收者手机号')),
                ('r_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='接收者昵称')),
                ('send_msg', models.TextField(blank=True, null=True, verbose_name='发送信息')),
                ('type', models.CharField(choices=[('1', '未读'), ('0', '已读')], default='0', max_length=6, verbose_name='消息状态')),
            ],
            options={
                'verbose_name': '用户聊天信息记录',
                'verbose_name_plural': '用户聊天信息记录',
            },
        ),
    ]
